name: sikucing
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: "^3.1.0"

dependencies:
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dropdown_search: ^5.0.6
  envied: ^0.3.0+3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  glassmorphism_ui: ^0.3.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  whatsapp_unilink: ^2.1.0

dev_dependencies:
  build_runner: ^2.4.6
  envied_generator: ^0.3.0+3
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/sikucing.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/splash/
    - assets/home/
